<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        Product::truncate();

        $products = [

            // ─────────────────────────────────────────────
            // AIR COOLED CHILLER
            // ─────────────────────────────────────────────
            [
                'name'              => 'Air Cooled Chiller 5 TR',
                'slug'              => 'air-cooled-chiller-5-tr',
                'category'          => 'Air Cooled Chiller',
                'short_description' => 'Unit chiller 5 Ton Refrigeration berpendingin udara, ideal untuk industri plastik dan manufaktur skala kecil.',
                'description'       => "Air Cooled Chiller 5 TR dari PT. Airindo Mitra Utama adalah solusi pendingin industri yang andal dan hemat energi. Menggunakan refrigeran ramah lingkungan R-410A, unit ini dirancang untuk beroperasi dalam kondisi lingkungan tropis Indonesia.\n\nCocok untuk industri plastik, manufaktur, dan proses produksi yang membutuhkan suhu stabil. Dilengkapi dengan sistem kontrol digital dan proteksi otomatis terhadap tekanan berlebih, overload, dan pembekuan.",
                'specifications'    => [
                    'Kapasitas Pendinginan' => '5 TR (17.6 kW)',
                    'Refrigeran'            => 'R-410A',
                    'Daya Input'            => '6.5 kW',
                    'COP'                   => '2.7',
                    'Tegangan'              => '3 Phase / 380V / 50Hz',
                    'Suhu Air Keluar'       => '7°C – 35°C',
                    'Flow Rate'             => '3.0 m³/jam',
                    'Koneksi Pipa'          => '1 inch',
                    'Dimensi (PxLxT)'       => '1100 x 500 x 1200 mm',
                    'Berat'                 => '180 kg',
                ],
                'shopee_link'       => 'https://shopee.co.id',
                'tokopedia_link'    => 'https://tokopedia.com',
                'is_active'         => true,
            ],
            [
                'name'              => 'Air Cooled Chiller 10 TR',
                'slug'              => 'air-cooled-chiller-10-tr',
                'category'          => 'Air Cooled Chiller',
                'short_description' => 'Unit chiller 10 Ton Refrigeration berpendingin udara untuk kebutuhan industri menengah dengan efisiensi energi tinggi.',
                'description'       => "Air Cooled Chiller 10 TR hadir sebagai solusi pendingin kapasitas menengah untuk pabrik dan fasilitas industri. Teknologi kompresor scroll ganda memberikan efisiensi tinggi dan keandalan operasional 24 jam.\n\nDilengkapi dengan panel kontrol PLC, sistem alarm otomatis, dan kemudahan perawatan berkat desain modular. Ideal untuk industri plastik injection, rubber, food & beverage, dan pharmaceutical.",
                'specifications'    => [
                    'Kapasitas Pendinginan' => '10 TR (35.2 kW)',
                    'Refrigeran'            => 'R-410A',
                    'Daya Input'            => '12.5 kW',
                    'COP'                   => '2.8',
                    'Tegangan'              => '3 Phase / 380V / 50Hz',
                    'Suhu Air Keluar'       => '7°C – 35°C',
                    'Flow Rate'             => '6.0 m³/jam',
                    'Koneksi Pipa'          => '1.5 inch',
                    'Dimensi (PxLxT)'       => '1600 x 700 x 1400 mm',
                    'Berat'                 => '320 kg',
                ],
                'shopee_link'       => 'https://shopee.co.id',
                'tokopedia_link'    => 'https://tokopedia.com',
                'is_active'         => true,
            ],
            [
                'name'              => 'Air Cooled Chiller 20 TR',
                'slug'              => 'air-cooled-chiller-20-tr',
                'category'          => 'Air Cooled Chiller',
                'short_description' => 'Unit chiller 20 TR kapasitas besar untuk pabrik dan fasilitas produksi industri berat.',
                'description'       => "Air Cooled Chiller 20 TR dirancang untuk memenuhi kebutuhan pendinginan industri berskala besar. Kompresor screw dengan inverter drive memberikan efisiensi tertinggi di kelasnya, menghemat konsumsi listrik hingga 30% dibanding unit konvensional.\n\nSistem kontrol touch screen intuitif memudahkan monitoring dan pengaturan. Konstruksi stainless steel pada komponen utama memastikan ketahanan jangka panjang di lingkungan industri.",
                'specifications'    => [
                    'Kapasitas Pendinginan' => '20 TR (70.3 kW)',
                    'Refrigeran'            => 'R-407C',
                    'Daya Input'            => '24 kW',
                    'COP'                   => '2.9',
                    'Tegangan'              => '3 Phase / 380V / 50Hz',
                    'Suhu Air Keluar'       => '5°C – 35°C',
                    'Flow Rate'             => '12.0 m³/jam',
                    'Koneksi Pipa'          => '2 inch',
                    'Dimensi (PxLxT)'       => '2400 x 900 x 1600 mm',
                    'Berat'                 => '680 kg',
                ],
                'shopee_link'       => 'https://shopee.co.id',
                'tokopedia_link'    => null,
                'is_active'         => true,
            ],

            // ─────────────────────────────────────────────
            // LINGHEIN (Atlas Copco Group)
            // ─────────────────────────────────────────────
            [
                'name'              => 'Linghein L-7.5A Screw Compressor 7.5 kW',
                'slug'              => 'linghein-l-7-5a-screw-compressor',
                'category'          => 'Linghein',
                'short_description' => 'Kompressor screw low-pressure Linghein 7.5 kW, ideal untuk industri plastik dan manufaktur ringan. Anak perusahaan Atlas Copco.',
                'description'       => "Linghein L-7.5A adalah kompressor screw low-pressure berteknologi tinggi dari Linghein, anak perusahaan Grup Atlas Copco Swedia. Dirancang khusus untuk kebutuhan industri plastik, blow molding, dan manufaktur ringan yang membutuhkan pasokan udara bertekanan rendah secara kontinyu.\n\nFitur oil-injection system memastikan pendinginan optimal dan umur panjang komponen. Sistem kontrol mikroprosessor memungkinkan pengoperasian otomatis dan monitoring kondisi mesin secara real-time.",
                'specifications'    => [
                    'Daya Motor'         => '7.5 kW (10 HP)',
                    'Tekanan Kerja'      => '0.7 – 1.0 MPa (7 – 10 bar)',
                    'Kapasitas Udara'    => '1.1 m³/menit',
                    'Kecepatan Rotor'    => '2950 rpm',
                    'Tegangan'           => '3 Phase / 380V / 50Hz',
                    'Jenis Kompresor'    => 'Twin Screw Oil-Injected',
                    'Pendinginan'        => 'Air Cooled',
                    'Tingkat Kebisingan' => '65 dB(A)',
                    'Dimensi (PxLxT)'   => '1000 x 600 x 900 mm',
                    'Berat'              => '220 kg',
                ],
                'shopee_link'       => 'https://shopee.co.id',
                'tokopedia_link'    => 'https://tokopedia.com',
                'is_active'         => true,
            ],
            [
                'name'              => 'Linghein L-15A Screw Compressor 15 kW',
                'slug'              => 'linghein-l-15a-screw-compressor',
                'category'          => 'Linghein',
                'short_description' => 'Kompressor screw Linghein 15 kW dengan efisiensi energi tinggi untuk produksi manufaktur kontinu.',
                'description'       => "Linghein L-15A menawarkan performa optimal untuk proses produksi yang membutuhkan pasokan udara bertekanan stabil dan kontinyu. Dilengkapi dengan sistem kontrol inverter opsional untuk mengoptimalkan konsumsi energi sesuai kebutuhan aktual.\n\nKonstruksi kokoh dengan material premium memastikan operasional andal 24/7. Perawatan mudah berkat akses panel yang luas dan desain modular. Garansi spare part tersedia dari gudang lokal PT. Airindo Mitra Utama.",
                'specifications'    => [
                    'Daya Motor'         => '15 kW (20 HP)',
                    'Tekanan Kerja'      => '0.7 – 1.0 MPa (7 – 10 bar)',
                    'Kapasitas Udara'    => '2.2 m³/menit',
                    'Kecepatan Rotor'    => '2950 rpm',
                    'Tegangan'           => '3 Phase / 380V / 50Hz',
                    'Jenis Kompresor'    => 'Twin Screw Oil-Injected',
                    'Pendinginan'        => 'Air Cooled',
                    'Tingkat Kebisingan' => '67 dB(A)',
                    'Dimensi (PxLxT)'   => '1100 x 700 x 1000 mm',
                    'Berat'              => '310 kg',
                ],
                'shopee_link'       => 'https://shopee.co.id',
                'tokopedia_link'    => 'https://tokopedia.com',
                'is_active'         => true,
            ],
            [
                'name'              => 'Linghein L-22A Screw Compressor 22 kW',
                'slug'              => 'linghein-l-22a-screw-compressor',
                'category'          => 'Linghein',
                'short_description' => 'Kompressor screw Linghein 22 kW berteknologi tinggi untuk industri manufaktur menengah dan berat.',
                'description'       => "Linghein L-22A adalah pilihan utama untuk industri manufaktur skala menengah dan berat. Teknologi rotor profil terbaru menghasilkan efisiensi volumetrik tertinggi di kelasnya, menghemat biaya listrik secara signifikan.\n\nDilengkapi sistem after-cooler terintegrasi untuk menurunkan suhu udara keluaran dan mengurangi kandungan uap air. Panel kontrol intelligent dengan touchscreen 7 inci memudahkan pengoperasian dan pemantauan.",
                'specifications'    => [
                    'Daya Motor'         => '22 kW (30 HP)',
                    'Tekanan Kerja'      => '0.7 – 1.3 MPa (7 – 13 bar)',
                    'Kapasitas Udara'    => '3.6 m³/menit',
                    'Kecepatan Rotor'    => '2950 rpm',
                    'Tegangan'           => '3 Phase / 380V / 50Hz',
                    'Jenis Kompresor'    => 'Twin Screw Oil-Injected',
                    'Pendinginan'        => 'Air Cooled',
                    'Tingkat Kebisingan' => '68 dB(A)',
                    'Dimensi (PxLxT)'   => '1300 x 800 x 1100 mm',
                    'Berat'              => '420 kg',
                ],
                'shopee_link'       => 'https://shopee.co.id',
                'tokopedia_link'    => 'https://tokopedia.com',
                'is_active'         => true,
            ],
            [
                'name'              => 'Linghein L-37A Screw Compressor 37 kW',
                'slug'              => 'linghein-l-37a-screw-compressor',
                'category'          => 'Linghein',
                'short_description' => 'Kompressor screw Linghein 37 kW berkapasitas tinggi dengan teknologi Atlas Copco untuk industri besar.',
                'description'       => "Linghein L-37A adalah unit kompressor screw berkapasitas tinggi untuk fasilitas produksi industri besar. Menggabungkan teknologi terdepan Atlas Copco dengan keandalan operasional jangka panjang.\n\nSistem pendinginan ganda memastikan suhu operasi optimal bahkan di lingkungan panas. Dilengkapi sistem monitoring jarak jauh melalui koneksi Ethernet/Modbus untuk integrasi dengan sistem SCADA pabrik.",
                'specifications'    => [
                    'Daya Motor'         => '37 kW (50 HP)',
                    'Tekanan Kerja'      => '0.7 – 1.3 MPa (7 – 13 bar)',
                    'Kapasitas Udara'    => '6.2 m³/menit',
                    'Kecepatan Rotor'    => '2950 rpm',
                    'Tegangan'           => '3 Phase / 380V / 50Hz',
                    'Jenis Kompresor'    => 'Twin Screw Oil-Injected',
                    'Pendinginan'        => 'Air Cooled',
                    'Tingkat Kebisingan' => '70 dB(A)',
                    'Dimensi (PxLxT)'   => '1600 x 950 x 1300 mm',
                    'Berat'              => '680 kg',
                ],
                'shopee_link'       => null,
                'tokopedia_link'    => 'https://tokopedia.com',
                'is_active'         => true,
            ],

            // ─────────────────────────────────────────────
            // JIANYE
            // ─────────────────────────────────────────────
            [
                'name'              => 'Jianye JY-7.5A Screw Compressor 7.5 kW',
                'slug'              => 'jianye-jy-7-5a-screw-compressor',
                'category'          => 'Jianye',
                'short_description' => 'Kompressor screw Jianye 7.5 kW dengan rasio harga dan performa terbaik untuk industri kecil dan menengah.',
                'description'       => "Kompressor screw Jianye JY-7.5A menghadirkan keandalan dan efisiensi untuk industri kecil dan menengah. Desain kompak dengan footprint minimal memudahkan instalasi di ruang terbatas.\n\nSistem pelumasan mandiri memastikan umur panjang komponen screw. Dilengkapi filter udara masuk tiga tahap untuk menghasilkan udara bersih dan kering. Mudah dioperasikan dan dirawat oleh teknisi lapangan.",
                'specifications'    => [
                    'Daya Motor'         => '7.5 kW (10 HP)',
                    'Tekanan Kerja'      => '0.7 – 1.0 MPa (7 – 10 bar)',
                    'Kapasitas Udara'    => '1.0 m³/menit',
                    'Tegangan'           => '3 Phase / 380V / 50Hz',
                    'Jenis Kompresor'    => 'Single Stage Screw',
                    'Pendinginan'        => 'Air Cooled',
                    'Tingkat Kebisingan' => '64 dB(A)',
                    'Tangki Udara'       => '270 Liter (opsional)',
                    'Dimensi (PxLxT)'   => '1050 x 620 x 950 mm',
                    'Berat'              => '200 kg',
                ],
                'shopee_link'       => 'https://shopee.co.id',
                'tokopedia_link'    => 'https://tokopedia.com',
                'is_active'         => true,
            ],
            [
                'name'              => 'Jianye JY-11A Screw Compressor 11 kW',
                'slug'              => 'jianye-jy-11a-screw-compressor',
                'category'          => 'Jianye',
                'short_description' => 'Kompressor screw Jianye 11 kW dengan desain kompak dan operasi senyap untuk lingkungan produksi.',
                'description'       => "Jianye JY-11A menawarkan kombinasi sempurna antara performa, efisiensi, dan kemudahan perawatan. Kabin akustik terintegrasi meredam kebisingan sehingga nyaman untuk lingkungan kerja.\n\nSistem kontrol elektronik otomatis mengatur tekanan kerja secara presisi dan mencegah pemborosan energi. Cocok untuk bengkel otomotif, industri elektronik, percetakan, dan manufaktur umum.",
                'specifications'    => [
                    'Daya Motor'         => '11 kW (15 HP)',
                    'Tekanan Kerja'      => '0.7 – 1.0 MPa (7 – 10 bar)',
                    'Kapasitas Udara'    => '1.65 m³/menit',
                    'Tegangan'           => '3 Phase / 380V / 50Hz',
                    'Jenis Kompresor'    => 'Single Stage Screw',
                    'Pendinginan'        => 'Air Cooled',
                    'Tingkat Kebisingan' => '65 dB(A)',
                    'Tangki Udara'       => '270 Liter (opsional)',
                    'Dimensi (PxLxT)'   => '1100 x 680 x 980 mm',
                    'Berat'              => '260 kg',
                ],
                'shopee_link'       => 'https://shopee.co.id',
                'tokopedia_link'    => 'https://tokopedia.com',
                'is_active'         => true,
            ],
            [
                'name'              => 'Jianye JY-15A Screw Compressor 15 kW',
                'slug'              => 'jianye-jy-15a-screw-compressor',
                'category'          => 'Jianye',
                'short_description' => 'Kompressor screw Jianye 15 kW kapasitas menengah dengan teknologi IE3 motor untuk efisiensi maksimal.',
                'description'       => "Jianye JY-15A hadir dengan motor IE3 (International Efficiency 3) yang memenuhi standar efisiensi energi internasional. Konsumsi energi lebih rendah 5–7% dibanding model sebelumnya dengan output yang sama.\n\nPenggantian oli dan filter mudah dilakukan tanpa harus membongkar unit. Suku cadang tersedia di gudang PT. Airindo Mitra Utama untuk meminimalkan downtime produksi.",
                'specifications'    => [
                    'Daya Motor'         => '15 kW (20 HP)',
                    'Tekanan Kerja'      => '0.7 – 1.3 MPa (7 – 13 bar)',
                    'Kapasitas Udara'    => '2.4 m³/menit',
                    'Tegangan'           => '3 Phase / 380V / 50Hz',
                    'Jenis Kompresor'    => 'Single Stage Screw',
                    'Kelas Motor'        => 'IE3',
                    'Pendinginan'        => 'Air Cooled',
                    'Tingkat Kebisingan' => '66 dB(A)',
                    'Dimensi (PxLxT)'   => '1200 x 720 x 1050 mm',
                    'Berat'              => '320 kg',
                ],
                'shopee_link'       => 'https://shopee.co.id',
                'tokopedia_link'    => null,
                'is_active'         => true,
            ],

            // ─────────────────────────────────────────────
            // RENNER
            // ─────────────────────────────────────────────
            [
                'name'              => 'Renner RS 7.5 Screw Compressor 7.5 kW',
                'slug'              => 'renner-rs-7-5-screw-compressor',
                'category'          => 'Renner',
                'short_description' => 'Kompressor screw Renner RS 7.5 kW buatan Jerman, berteknologi presisi tinggi untuk kebutuhan industri dan otomotif.',
                'description'       => "Renner RS Series adalah kompressor screw premium buatan Jerman yang terkenal dengan presisi, keandalan, dan umur panjang. Rotor screw dibuat dengan toleransi sangat ketat menggunakan CNC machining untuk efisiensi volumetrik tertinggi.\n\nDigunakan secara luas di industri otomotif, aerospace, farmasi, dan manufaktur presisi yang menuntut kualitas udara terbaik. Dilengkapi dengan oil separator efisiensi tinggi untuk kandungan oli residual di bawah 2 ppm.",
                'specifications'    => [
                    'Daya Motor'          => '7.5 kW (10 HP)',
                    'Tekanan Kerja'       => '0.8 – 1.0 MPa (8 – 10 bar)',
                    'Kapasitas Udara'     => '1.05 m³/menit',
                    'Tegangan'            => '3 Phase / 380V / 50Hz',
                    'Jenis Kompresor'     => 'Oil-Injected Screw',
                    'Pendinginan'         => 'Air Cooled',
                    'Kandungan Oli'       => '< 2 ppm',
                    'Tingkat Kebisingan'  => '63 dB(A)',
                    'Negara Manufaktur'   => 'Germany',
                    'Dimensi (PxLxT)'    => '1020 x 580 x 920 mm',
                    'Berat'               => '215 kg',
                ],
                'shopee_link'       => 'https://shopee.co.id',
                'tokopedia_link'    => 'https://tokopedia.com',
                'is_active'         => true,
            ],
            [
                'name'              => 'Renner RS 11 Screw Compressor 11 kW',
                'slug'              => 'renner-rs-11-screw-compressor',
                'category'          => 'Renner',
                'short_description' => 'Kompressor screw Renner RS 11 kW made in Germany, standar Eropa dengan konsumsi energi optimal.',
                'description'       => "Renner RS 11 menghadirkan standar kualitas Eropa dalam paket yang kompak dan efisien. Motor premium IE3 berpasangan dengan rotor screw presisi Renner menghasilkan efisiensi spesifik terbaik di kelasnya.\n\nSistem kontrol DELCOS XL memungkinkan pengaturan parameter operasi secara detail, scheduling otomatis, dan konektivitas remote untuk monitoring jarak jauh. Intervalisme perawatan yang panjang (6.000 jam) meminimalkan biaya operasional.",
                'specifications'    => [
                    'Daya Motor'          => '11 kW (15 HP)',
                    'Tekanan Kerja'       => '0.8 – 1.3 MPa (8 – 13 bar)',
                    'Kapasitas Udara'     => '1.6 m³/menit',
                    'Tegangan'            => '3 Phase / 380V / 50Hz',
                    'Jenis Kompresor'     => 'Oil-Injected Screw',
                    'Pendinginan'         => 'Air Cooled',
                    'Kandungan Oli'       => '< 2 ppm',
                    'Tingkat Kebisingan'  => '64 dB(A)',
                    'Interval Perawatan'  => '6.000 jam',
                    'Negara Manufaktur'   => 'Germany',
                    'Dimensi (PxLxT)'    => '1100 x 640 x 980 mm',
                    'Berat'               => '275 kg',
                ],
                'shopee_link'       => 'https://shopee.co.id',
                'tokopedia_link'    => 'https://tokopedia.com',
                'is_active'         => true,
            ],
            [
                'name'              => 'Renner RS 15 Screw Compressor 15 kW',
                'slug'              => 'renner-rs-15-screw-compressor',
                'category'          => 'Renner',
                'short_description' => 'Kompressor screw Renner RS 15 kW berteknologi Jerman untuk produksi industri 24 jam non-stop.',
                'description'       => "Renner RS 15 adalah pilihan unggulan untuk fasilitas produksi yang beroperasi 24 jam tanpa henti. Desain termal yang optimal mencegah overheat bahkan pada kondisi operasi kontinu di iklim tropis.\n\nFrame baja galvanized anti-karat memastikan ketahanan terhadap kondisi pabrik yang lembab. Sertifikasi CE dan ISO 1217 memenuhi persyaratan standar industri internasional dan ekspor.",
                'specifications'    => [
                    'Daya Motor'          => '15 kW (20 HP)',
                    'Tekanan Kerja'       => '0.8 – 1.3 MPa (8 – 13 bar)',
                    'Kapasitas Udara'     => '2.3 m³/menit',
                    'Tegangan'            => '3 Phase / 380V / 50Hz',
                    'Jenis Kompresor'     => 'Oil-Injected Screw',
                    'Pendinginan'         => 'Air Cooled',
                    'Kandungan Oli'       => '< 2 ppm',
                    'Tingkat Kebisingan'  => '65 dB(A)',
                    'Sertifikasi'         => 'CE, ISO 1217',
                    'Interval Perawatan'  => '6.000 jam',
                    'Negara Manufaktur'   => 'Germany',
                    'Dimensi (PxLxT)'    => '1250 x 720 x 1080 mm',
                    'Berat'               => '350 kg',
                ],
                'shopee_link'       => null,
                'tokopedia_link'    => 'https://tokopedia.com',
                'is_active'         => true,
            ],

        ];

        foreach ($products as $data) {
            Product::create($data);
        }
    }
}
